<?php
/**
 * Theme functions and definitions.
 * This child theme was generated by Merlin WP.
 *
 * @link https://developer.wordpress.org/themes/basics/theme-functions/
 */

/*
 * If your child theme has more than one .css file (eg. ie.css, style.css, main.css) then
 * you will have to make sure to maintain all of the parent theme dependencies.
 *
 * Make sure you're using the correct handle for loading the parent theme's styles.
 * Failure to use the proper tag will result in a CSS file needlessly being loaded twice.
 * This will usually not affect the site appearance, but it's inefficient and extends your page's loading time.
 *
 * @link https://codex.wordpress.org/Child_Themes
 */
function furnob_child_enqueue_styles() {
    wp_enqueue_style( 'parent-style', get_template_directory_uri() . '/style.css' );
    wp_enqueue_style( 'furnob-child-style',
        get_stylesheet_directory_uri() . '/style.css',
        array( 'furnob-style' ),
        wp_get_theme()->get('Version')
    );
}

add_action( 'wp_enqueue_scripts', 'furnob_child_enqueue_styles', 99 );

/*************************************************
## Fix: Related Products int casting (WC 10.x strict typing)
## Parent theme passes string '4' to woocommerce_related_products(),
## but WC 10.x requires int parameters.
*************************************************/
remove_action( 'woocommerce_after_single_product_summary', 'furnob_related_products', 20 );
add_action( 'woocommerce_after_single_product_summary', 'furnob_child_related_products', 20 );
function furnob_child_related_products() {
    $related_column = (int) get_theme_mod( 'furnob_shop_related_post_column', 4 );
    woocommerce_related_products( array(
        'posts_per_page' => $related_column,
        'columns'        => $related_column,
    ) );
}

/*************************************************
## Performance Optimizations
## Safe to remove — just delete this section to revert.
*************************************************/

/**
 * Preconnect for Google Fonts (saves DNS+TLS handshake ~100-300ms).
 */
function furnob_child_resource_hints( $urls, $relation_type ) {
    if ( 'preconnect' === $relation_type ) {
        $urls[] = array(
            'href'        => 'https://fonts.googleapis.com',
            'crossorigin' => '',
        );
        $urls[] = array(
            'href'        => 'https://fonts.gstatic.com',
            'crossorigin' => 'anonymous',
        );
    }
    return $urls;
}
add_filter( 'wp_resource_hints', 'furnob_child_resource_hints', 10, 2 );

/**
 * Optimize Google Fonts: 8 variants instead of 18 + display=swap.
 */
function furnob_child_optimize_google_fonts( $src, $handle ) {
    if ( 'furnob-font-jost' === $handle && false !== strpos( $src, 'fonts.googleapis.com' ) ) {
        $src = add_query_arg( array(
            'family'  => 'Jost:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700',
            'display' => 'swap',
        ), 'https://fonts.googleapis.com/css2' );
    }
    return $src;
}
add_filter( 'style_loader_src', 'furnob_child_optimize_google_fonts', 10, 2 );

/**
 * Lazy loading on WooCommerce cart/mini-cart thumbnails.
 */
function furnob_child_lazy_load_cart_images( $thumbnail, $cart_item, $cart_item_key ) {
    if ( false === strpos( $thumbnail, 'loading=' ) ) {
        $thumbnail = str_replace( '<img ', '<img loading="lazy" ', $thumbnail );
    }
    return $thumbnail;
}
add_filter( 'woocommerce_cart_item_thumbnail', 'furnob_child_lazy_load_cart_images', 10, 3 );

/*************************************************
## Kirki-independent customizer CSS
## The Furnob theme expects the Kirki Customizer Framework to read theme_mods
## and emit inline CSS (logo size, colors, etc.). Without Kirki, those styles
## are missing — the logo overflows the header. This emits the most-used rules
## directly from theme_mods so the theme renders correctly.
*************************************************/
function furnob_child_inline_customizer_css() {
	$mods = get_theme_mod_values_for_inline_css();

	$rules = array();

	// Logo sizes
	if ( ! empty( $mods['furnob_logo_size'] ) ) {
		$rules[] = '.site-header .site-brand img { width: ' . intval( $mods['furnob_logo_size'] ) . 'px; height: auto; }';
	}
	if ( ! empty( $mods['furnob_mobil_logo_size'] ) ) {
		$rules[] = '.site-header .header-mobile .site-brand img { width: ' . intval( $mods['furnob_mobil_logo_size'] ) . 'px; height: auto; }';
	}
	if ( ! empty( $mods['furnob_sidebar_logo_size'] ) ) {
		$rules[] = '.site-offcanvas-header .site-brand img { width: ' . intval( $mods['furnob_sidebar_logo_size'] ) . 'px; height: auto; }';
	}

	// Main + secondary palette
	if ( ! empty( $mods['furnob_main_color'] ) ) {
		$c = sanitize_hex_color( $mods['furnob_main_color'] );
		if ( $c ) {
			$rules[] = ':root { --furnob-main-color: ' . $c . '; }';
			$rules[] = '.btn-primary, .button.alt, .woocommerce #respond input#submit.alt, .woocommerce a.button.alt, .woocommerce button.button.alt, .woocommerce input.button.alt { background-color: ' . $c . '; border-color: ' . $c . '; }';
			$rules[] = 'a:hover, .site-header .site-nav a:hover, .product-title a:hover { color: ' . $c . '; }';
		}
	}
	if ( ! empty( $mods['furnob_second_color'] ) ) {
		$c = sanitize_hex_color( $mods['furnob_second_color'] );
		if ( $c ) {
			$rules[] = ':root { --furnob-second-color: ' . $c . '; }';
		}
	}

	// Header type 5 colors (active header type per theme_mods)
	$h5_map = array(
		'furnob_header5_top_bg_color'      => '.site-header.header-type5 .header-top { background-color: %s; }',
		'furnob_header5_top_font_color'    => '.site-header.header-type5 .header-top, .site-header.header-type5 .header-top a { color: %s; }',
		'furnob_header5_main_bg_color'     => '.site-header.header-type5 .header-main { background-color: %s; }',
		'furnob_header5_main_border_color' => '.site-header.header-type5 .header-main { border-color: %s; }',
		'furnob_header5_bottom_bg_color'   => '.site-header.header-type5 .header-bottom { background-color: %s; }',
	);
	foreach ( $h5_map as $key => $tpl ) {
		if ( ! empty( $mods[ $key ] ) ) {
			$c = sanitize_hex_color( $mods[ $key ] );
			if ( $c ) {
				$rules[] = sprintf( $tpl, $c );
			}
		}
	}

	// Footer colors
	$footer_map = array(
		'furnob_footer_top_bg_color'        => '.site-footer .footer-top { background-color: %s; }',
		'furnob_footer_top_border_color'    => '.site-footer .footer-top { border-color: %s; }',
		'furnob_footer_bottom_bg_color'     => '.site-footer .footer-bottom { background-color: %s; }',
		'furnob_footer_bottom_border_color' => '.site-footer .footer-bottom { border-color: %s; }',
		'furnob_footer_title_color'         => '.site-footer .widget-title, .site-footer .widget h4 { color: %s; }',
		'furnob_footer_subtitle_color'      => '.site-footer p, .site-footer li, .site-footer a { color: %s; }',
		'furnob_footer_payment_color'       => '.site-footer .payment-icons i { color: %s; }',
	);
	foreach ( $footer_map as $key => $tpl ) {
		if ( ! empty( $mods[ $key ] ) ) {
			$c = sanitize_hex_color( $mods[ $key ] );
			if ( $c ) {
				$rules[] = sprintf( $tpl, $c );
			}
		}
	}

	// Featured boxes (footer top)
	$fb_map = array(
		'furnob_featured_box_icon_color'  => '.featured-box .featured-icon { color: %s; }',
		'furnob_featured_box_title_color' => '.featured-box .featured-title { color: %s; }',
		'furnob_featured_box_desc_color'  => '.featured-box .featured-content { color: %s; }',
	);
	foreach ( $fb_map as $key => $tpl ) {
		if ( ! empty( $mods[ $key ] ) ) {
			$c = sanitize_hex_color( $mods[ $key ] );
			if ( $c ) {
				$rules[] = sprintf( $tpl, $c );
			}
		}
	}

	if ( empty( $rules ) ) return;

	echo "\n<style id=\"furnob-child-customizer-fallback\">\n" . implode( "\n", $rules ) . "\n</style>\n";
}
add_action( 'wp_head', 'furnob_child_inline_customizer_css', 100 );

function get_theme_mod_values_for_inline_css() {
	static $cache = null;
	if ( $cache !== null ) return $cache;
	$keys = array(
		'furnob_logo_size', 'furnob_mobil_logo_size', 'furnob_sidebar_logo_size',
		'furnob_main_color', 'furnob_second_color',
		'furnob_header5_top_bg_color', 'furnob_header5_top_font_color',
		'furnob_header5_main_bg_color', 'furnob_header5_main_border_color',
		'furnob_header5_bottom_bg_color',
		'furnob_footer_top_bg_color', 'furnob_footer_top_border_color',
		'furnob_footer_bottom_bg_color', 'furnob_footer_bottom_border_color',
		'furnob_footer_title_color', 'furnob_footer_subtitle_color',
		'furnob_footer_payment_color',
		'furnob_featured_box_icon_color', 'furnob_featured_box_title_color',
		'furnob_featured_box_desc_color',
	);
	$cache = array();
	foreach ( $keys as $k ) {
		$cache[ $k ] = get_theme_mod( $k );
	}
	return $cache;
}